In [6]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [7]:
df = pd.read_csv('/content/IPL_Matches_tail_300.csv')
print(df.shape)

(300, 25)

In [8]:
df.tail().isnull().sum().sort_values(ascending=False)

team1_runs         1
winner             1
player_of_match    1
team2_runs         1
date               0
team1              0
season             0
venue              0
city               0
toss_decision      0
toss_winner        0
team2              0
team1_wickets      0
team2_wickets      0
result_type        0
win_by_runs        0
win_by_wickets     0
match_referee      0
umpire1            0
umpire2            0
tv_umpire          0
reserve_umpire     0
overs_limit        0
team1_players      0
team2_players      0
dtype: int64

# Mean Imputation

In [9]:
mean_df = df.copy()
mean_value = mean_df['team1_runs'].mean()
mean_value

np.float64(188.13651877133105)

In [10]:
mean_df['team1_runs']=mean_df['team1_runs'].fillna(mean_value)
mean_df['team1_runs'].isnull().sum()

np.int64(0)

In [16]:
df3=df.select_dtypes("object")

In [ ]:
df3['winner'].value_counts(normalize=True)

In [23]:
df.pivot_table(values='winner',index=['venue'],columns=['toss_decision'],aggfunc="count")

toss_decision                                        bat  field
venue
Arun Jaitley Stadium, Delhi                          6.0   19.0
Barsapara Cricket Stadium, Guwahati                  1.0    7.0
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cr...   6.0   21.0
Brabourne Stadium, Mumbai                            1.0    NaN
Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Sta...   3.0    1.0
Eden Gardens, Kolkata                                5.0   22.0
Himachal Pradesh Cricket Association Stadium, D...   0.0    9.0
M Chinnaswamy Stadium, Bengaluru                     NaN   24.0
MA Chidambaram Stadium, Chepauk, Chennai            10.0   21.0
Maharaja Yadavindra Singh International Cricket...   3.0    5.0
Maharaja Yadavindra Singh International Cricket...   2.0    5.0
Narendra Modi Stadium, Ahmedabad                     7.0   27.0
Punjab Cricket Association IS Bindra Stadium, M...   NaN    5.0
Rajiv Gandhi International Stadium, Uppal, Hyde...  10.0   15.0
Sawai Mansingh Stadium, Jaipur                       9.0   12.0
Shaheed Veer Narayan Singh International Stadiu...   NaN    2.0
Wankhede Stadium, Mumbai                             3.0   27.0

In [27]:
df5 =df.select_dtypes("number")

In [29]:
df5.skew().index

Index(['season', 'team1_runs', 'team1_wickets', 'team2_runs', 'team2_wickets',
       'win_by_runs', 'win_by_wickets', 'overs_limit'],
      dtype='object')

In [ ]:
import seaborn as sns
sns.heatmap()