In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('/content/IPLPlayerStat.csv')

In [3]:
df.isna().sum()

Unnamed: 0             0
player                 0
runs                   0
boundaries             0
balls_faced            0
wickets                0
balls_bowled           0
runs_conceded          0
matches                0
batting_avg            0
batting_strike_rate    0
boundaries_percent     0
bowling_economy        0
bowling_avg            0
bowling_strike_rate    0
catches                0
stumpings              0
dtype: int64

In [29]:
X = df[['balls_faced']]
y = df['runs']

X_train , X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=42)

model = LinearRegression()
model.fit(X_train,y_train)

predict = model.predict(X_test)

pd.DataFrame({
    'Actual Ball':X_test['balls_faced'].values,
    'Actual Runs':y_test.values,
    'Predicted Runs': np.round(predict[0],2)
})

     Actual Ball  Actual Runs  Predicted Runs
0            434          522          542.09
1             27           40          542.09
2             57           76          542.09
3             31           21          542.09
4            552          663          542.09
..           ...          ...             ...
116          758         1001          542.09
117            4            0          542.09
118           23           26          542.09
119           32           31          542.09
120          173          180          542.09

[121 rows x 3 columns]