In [1]:
import pandas as pd
df = pd.read_csv('class_ipl_22-26_dataset.csv')
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [3]:
num_col = df.select_dtypes(include='number').columns
num_col

Index(['season', 'team1_runs', 'team1_wickets', 'team2_runs', 'team2_wickets',
       'win_by_runs', 'win_by_wickets', 'overs_limit'],
      dtype='object')

In [4]:
df.columns

Index(['date', 'season', 'city', 'venue', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'team1_runs', 'team1_wickets', 'team2_runs',
       'team2_wickets', 'winner', 'result_type', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'match_referee', 'umpire1',
       'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players'],
      dtype='object')

In [6]:
mean_value = df[num_col].mean()
print(mean_value)

season            2024.000000
team1_runs         185.070845
team1_wickets        6.242507
team2_runs         169.250681
team2_wickets        5.926431
win_by_runs         15.343324
win_by_wickets       3.049046
overs_limit         20.000000
dtype: float64

In [7]:
median_value = df[num_col].median()
print(median_value)

season            2024.0
team1_runs         187.0
team1_wickets        6.0
team2_runs         171.0
team2_wickets        6.0
win_by_runs          0.0
win_by_wickets       2.0
overs_limit         20.0
dtype: float64

In [8]:
mode_value = df['team1_runs'].mode()
print(mode_value)

0    159
1    162
Name: team1_runs, dtype: int64

In [9]:
df['team1_runs'].value_counts()

team1_runs
162    8
159    8
155    7
210    7
214    7
      ..
242    1
75     1
225    1
247    1
255    1
Name: count, Length: 137, dtype: int64

In [10]:
std_value = df[num_col].std()
print(std_value)

season             1.421921
team1_runs        36.516265
team1_wickets      2.173749
team2_runs        38.827661
team2_wickets      2.740614
win_by_runs       24.782703
win_by_wickets     3.243791
overs_limit        0.000000
dtype: float64

In [11]:
df.describe()

,season,team1_runs,team1_wickets,team2_runs,team2_wickets,win_by_runs,win_by_wickets,overs_limit
count,367.000000,367.000000,367.000000,367.000000,367.000000,367.000000,367.000000,367.0
mean,2024.000000,185.070845,6.242507,169.250681,5.926431,15.343324,3.049046,20.0
std,1.421921,36.516265,2.173749,38.827661,2.740614,24.782703,3.243791,0.0
min,2022.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.0
25%,2023.000000,161.500000,5.000000,150.500000,4.000000,0.000000,0.000000,20.0
50%,2024.000000,187.000000,6.000000,171.000000,6.000000,0.000000,2.000000,20.0
75%,2025.000000,209.000000,8.000000,196.000000,8.000000,23.000000,6.000000,20.0
max,2026.000000,287.000000,10.000000,265.000000,10.000000,112.000000,10.000000,20.0