In [13]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [2]:
df = pd.read_csv('class_ipl_22-26_dataset_with_nulls.csv')
print(df.shape)
df.head()

(367, 25)

         date  ...                                      team2_players
0  26-03-2022  ...  AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin...
1  27-03-2022  ...  PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L...
2  27-03-2022  ...  MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living...
3  28-03-2022  ...  Shubman Gill, MS Wade, V Shankar, HH Pandya, D...
4  29-03-2022  ...  KS Williamson, Abhishek Sharma, RA Tripathi, N...

[5 rows x 25 columns]

In [3]:
# missing value summery
df.isnull().sum()

date                0
season              0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets      12
team2_runs          0
team2_wickets       0
winner              7
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     5
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
overs_limit         0
team1_players       0
team2_players       0
dtype: int64

In [4]:
mean_df = df.copy()
mean_value = mean_df['team1_runs'].mean()
print(mean_value)

185.0708446866485

In [5]:
mean_df['team1_runs']=mean_df['team1_runs'].fillna(mean_value)
mean_df['team1_runs'].isnull().sum()

np.int64(0)

In [6]:
mean_df.isnull().sum()

date                0
season              0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets      12
team2_runs          0
team2_wickets       0
winner              7
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     5
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
overs_limit         0
team1_players       0
team2_players       0
dtype: int64

In [7]:
median_df = df.copy()
median_value = median_df['team2_runs'].median()
print(median_value)

171.0

In [8]:
median_df['team2_runs']=median_df['team2_runs'].fillna(median_value)
median_df['team2_runs'].isnull().sum()

np.int64(0)

In [9]:
mode_df = df.copy()
mode_df[['winner','player_of_match']].isnull().sum()

winner             7
player_of_match    5
dtype: int64

In [10]:
mode_df['winner']= mode_df['winner'].fillna(mode_df['winner'].mode()[0])
mode_df['player_of_match']=mode_df['player_of_match'].fillna(mode_df['player_of_match'].mode()[0])

mode_df[['winner','player_of_match']].isnull().sum()

winner             0
player_of_match    0
dtype: int64

# Simple Imputer

In [11]:
df.isnull().sum()

date                0
season              0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets      12
team2_runs          0
team2_wickets       0
winner              7
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     5
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
overs_limit         0
team1_players       0
team2_players       0
dtype: int64

In [18]:
mean_imp = SimpleImputer(strategy='mean')
median_imp = SimpleImputer(strategy='median')
mode_imp = SimpleImputer(strategy='most_frequent')

df['team1_wickets'] = mean_imp.fit_transform(df[['team1_wickets']])
df['team2_runs']=median_imp.fit_transform(df[['team2_runs']])
df[['winner']]=mode_imp.fit_transform(df[['winner']])
df[['player_of_match']]=mode_imp.fit_transform(df[['player_of_match']])

df.isnull().sum()

date               0
season             0
city               0
venue              0
team1              0
team2              0
toss_winner        0
toss_decision      0
team1_runs         0
team1_wickets      0
team2_runs         0
team2_wickets      0
winner             0
result_type        0
win_by_runs        0
win_by_wickets     0
player_of_match    0
match_referee      0
umpire1            0
umpire2            0
tv_umpire          0
reserve_umpire     0
overs_limit        0
team1_players      0
team2_players      0
dtype: int64